/**
 * generated by Xtext 2.12.0
 */
package org.xtext.hLCLSpecificationLanguage.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;

import org.xtext.hLCLSpecificationLanguage.HLCLSpecificationLanguagePackage;
import org.xtext.hLCLSpecificationLanguage.SetRefinement;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Set Refinement</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.hLCLSpecificationLanguage.impl.SetRefinementImpl#getVars <em>Vars</em>}</li>
 *   <li>{@link org.xtext.hLCLSpecificationLanguage.impl.SetRefinementImpl#getHead <em>Head</em>}</li>
 *   <li>{@link org.xtext.hLCLSpecificationLanguage.impl.SetRefinementImpl#getTail <em>Tail</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SetRefinementImpl extends RefinementImpl implements SetRefinement
{
  /**
   * The default value of the '{@link #getVars() <em>Vars</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVars()
   * @generated
   * @ordered
   */
  protected static final String VARS_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getVars() <em>Vars</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVars()
   * @generated
   * @ordered
   */
  protected String vars = VARS_EDEFAULT;

  /**
   * The default value of the '{@link #getHead() <em>Head</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHead()
   * @generated
   * @ordered
   */
  protected static final String HEAD_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getHead() <em>Head</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHead()
   * @generated
   * @ordered
   */
  protected String head = HEAD_EDEFAULT;

  /**
   * The cached value of the '{@link #getTail() <em>Tail</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTail()
   * @generated
   * @ordered
   */
  protected EList<String> tail;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SetRefinementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return HLCLSpecificationLanguagePackage.Literals.SET_REFINEMENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getVars()
  {
    return vars;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setVars(String newVars)
  {
    String oldVars = vars;
    vars = newVars;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, HLCLSpecificationLanguagePackage.SET_REFINEMENT__VARS, oldVars, vars));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getHead()
  {
    return head;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setHead(String newHead)
  {
    String oldHead = head;
    head = newHead;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, HLCLSpecificationLanguagePackage.SET_REFINEMENT__HEAD, oldHead, head));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<String> getTail()
  {
    if (tail == null)
    {
      tail = new EDataTypeEList<String>(String.class, this, HLCLSpecificationLanguagePackage.SET_REFINEMENT__TAIL);
    }
    return tail;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case HLCLSpecificationLanguagePackage.SET_REFINEMENT__VARS:
        return getVars();
      case HLCLSpecificationLanguagePackage.SET_REFINEMENT__HEAD:
        return getHead();
      case HLCLSpecificationLanguagePackage.SET_REFINEMENT__TAIL:
        return getTail();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case HLCLSpecificationLanguagePackage.SET_REFINEMENT__VARS:
        setVars((String)newValue);
        return;
      case HLCLSpecificationLanguagePackage.SET_REFINEMENT__HEAD:
        setHead((String)newValue);
        return;
      case HLCLSpecificationLanguagePackage.SET_REFINEMENT__TAIL:
        getTail().clear();
        getTail().addAll((Collection<? extends String>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case HLCLSpecificationLanguagePackage.SET_REFINEMENT__VARS:
        setVars(VARS_EDEFAULT);
        return;
      case HLCLSpecificationLanguagePackage.SET_REFINEMENT__HEAD:
        setHead(HEAD_EDEFAULT);
        return;
      case HLCLSpecificationLanguagePackage.SET_REFINEMENT__TAIL:
        getTail().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case HLCLSpecificationLanguagePackage.SET_REFINEMENT__VARS:
        return VARS_EDEFAULT == null ? vars != null : !VARS_EDEFAULT.equals(vars);
      case HLCLSpecificationLanguagePackage.SET_REFINEMENT__HEAD:
        return HEAD_EDEFAULT == null ? head != null : !HEAD_EDEFAULT.equals(head);
      case HLCLSpecificationLanguagePackage.SET_REFINEMENT__TAIL:
        return tail != null && !tail.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (vars: ");
    result.append(vars);
    result.append(", head: ");
    result.append(head);
    result.append(", tail: ");
    result.append(tail);
    result.append(')');
    return result.toString();
  }

} //SetRefinementImpl
