/**
 * generated by Xtext 2.12.0
 */
package com.coffee.pLEC;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.coffee.pLEC.PLECPackage#getExpression()
 * @model
 * @generated
 */
public interface Expression extends EObject
{
} // Expression
