/**
 * generated by Xtext 2.12.0
 */
package com.coffee.hlvl.hLVL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Options Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.coffee.hlvl.hLVL.HLVLPackage#getOptionsDeclaration()
 * @model
 * @generated
 */
public interface OptionsDeclaration extends EObject
{
} // OptionsDeclaration
