/*
 * generated by Xtext 2.12.0
 */
package com.coffee.ui.tests;

import com.coffee.plec.ui.internal.PlecActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class PLECUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return PlecActivator.getInstance().getInjector("com.coffee.PLEC");
	}

}
