/**
 * generated by Xtext 2.12.0
 */
package com.coffee.hlvl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Cons Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.coffee.hlvl.HlvlPackage#getConsExpression()
 * @model
 * @generated
 */
public interface ConsExpression extends EObject
{
} // ConsExpression
