/**
 * generated by Xtext 2.12.0
 */
package com.coffee.hlvl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Num Conf</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.coffee.hlvl.HlvlPackage#getNumConf()
 * @model
 * @generated
 */
public interface NumConf extends Operation
{
} // NumConf
