/**
 * generated by Xtext 2.12.0
 */
package com.coffee.pLEC;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Symbol</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.coffee.pLEC.PLECPackage#getSymbol()
 * @model
 * @generated
 */
public interface Symbol extends NonEnumerableValue
{
} // Symbol
