/**
 * generated by Xtext 2.12.0
 */
package com.coffee.ide;

import com.coffee.HlvlRuntimeModule;
import com.coffee.HlvlStandaloneSetup;
import com.coffee.ide.HlvlIdeModule;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class HlvlIdeSetup extends HlvlStandaloneSetup {
  @Override
  public Injector createInjector() {
    HlvlRuntimeModule _hlvlRuntimeModule = new HlvlRuntimeModule();
    HlvlIdeModule _hlvlIdeModule = new HlvlIdeModule();
    return Guice.createInjector(Modules2.mixin(_hlvlRuntimeModule, _hlvlIdeModule));
  }
}
