/**
 * generated by Xtext 2.12.0
 */
package com.coffee.tHLCL.impl;

import com.coffee.tHLCL.Relational;
import com.coffee.tHLCL.THLCLPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Relational</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class RelationalImpl extends ExpressionImpl implements Relational
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RelationalImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return THLCLPackage.Literals.RELATIONAL;
  }

} //RelationalImpl
