/**
 * generated by Xtext 2.12.0
 */
package org.xtext.pLhlcl.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.pLhlcl.BoolVal;
import org.xtext.pLhlcl.PLhlclPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Bool Val</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class BoolValImpl extends NonEnumerableValueImpl implements BoolVal
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BoolValImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PLhlclPackage.Literals.BOOL_VAL;
  }

} //BoolValImpl
