//Java imports
import java.util.HashMap;
import java.util.List;
//imports for hlcl 
import com.variamos.hlcl.core.HlclProgram; 
import com.variamos.hlcl.model.expressions.HlclFactory; 
import com.variamos.hlcl.model.domains.BinaryDomain;
import com.variamos.hlcl.model.domains.IntervalDomain;
import com.variamos.hlcl.model.domains.RangeDomain;
import com.variamos.hlcl.model.domains.StringDomain;
import com.variamos.hlcl.model.expressions.Identifier;
import com.variamos.hlcl.model.expressions.IntBooleanExpression;
import com.variamos.hlcl.model.expressions.NumericIdentifier;
import com.variamos.hlcl.model.expressions.SymbolicExpression;
import com.variamos.hlcl.model.expressions.IntNumericExpression;

//imports for solver
import com.variamos.solver.core.SWIPrologSolver;
import com.variamos.solver.core.compiler.Hlcl2SWIProlog;
import com.variamos.solver.model.SolverSolution;

/**
* This class is automatically generated from a product line model described in 
* constraint programming HLCL
* @author Angela Villota 
* @version CP-HLCL Version1
*
*/
public class Attributes_HLVL { 			
	
	private String modelName;
	private HlclFactory factory;
	private HlclProgram hlclProgram;
	private SWIPrologSolver swiSolver;
	private String prologProgram;
	private HashMap<String,IntBooleanExpression> constraints;
	private HashMap<String,Identifier> variables;
	private HashMap<String,NumericIdentifier> numbers;
	/**
	* This is an autogenerated method* Constructor method
	* @param modelName is the name of the model in the  CP-HLCL specification
	*/
	public Attributes_HLVL(String modelName){ 				
		
		this.modelName= modelName;
		hlclProgram= new HlclProgram();
		factory = new HlclFactory();
		variables= new HashMap<String,Identifier>();
		constraints= new HashMap<String,IntBooleanExpression>();
		numbers= new HashMap<String,NumericIdentifier>();
		NumericIdentifier one = factory.number(1);
		NumericIdentifier zero= factory.number(0);
		numbers.put("1", one);
		numbers.put("0", zero);
	} 			
	public static void main(String[] args) {
		Attributes_HLVL obj = new Attributes_HLVL("Attributes_HLVL");
		obj.run();
	}
	public void run(){
		// first obtain a HlclProgram from the specification
		transformVars();
		transformConstraints(); 
		// use the solver to solve the constraint program
		evaluateSatisfiability();
		//show the output
		System.out.println(prologProgram);
	}
	public void transformVars() {
//declaring variable MCS
Identifier MCS = factory.newIdentifier("MCS");
  			BinaryDomain MCSDom= new BinaryDomain();
MCS.setDomain(MCSDom);	
variables.put("MCS", MCS); //including the variable in the map
//declaring variable Memory
Identifier Memory = factory.newIdentifier("Memory");
  			BinaryDomain MemoryDom= new BinaryDomain();
Memory.setDomain(MemoryDom);	
variables.put("Memory", Memory); //including the variable in the map
//declaring variable Processor
Identifier Processor = factory.newIdentifier("Processor");
  			BinaryDomain ProcessorDom= new BinaryDomain();
Processor.setDomain(ProcessorDom);	
variables.put("Processor", Processor); //including the variable in the map
//declaring variable Cores
Identifier Cores = factory.newIdentifier("Cores");
 				RangeDomain CoresDom= new RangeDomain(0, 7);
Cores.setDomain(CoresDom);	
variables.put("Cores", Cores); //including the variable in the map
//declaring variable Size
Identifier Size = factory.newIdentifier("Size");
 				RangeDomain SizeDom= new RangeDomain(0, 32);
Size.setDomain(SizeDom);	
variables.put("Size", Size); //including the variable in the map
	}
	public void transformConstraints() {
//
//declaring constraint C2


Identifier C2_left = variables.get("MCS");

Identifier C2_right = variables.get("Processor");
IntBooleanExpression C2=
factory.greaterOrEqualsThan(C2_left, C2_right);
constraints.put("C2", C2);
hlclProgram.add(C2);
//
//declaring constraint C4


Identifier C4_left = variables.get("Processor");

Identifier C4_right = variables.get("Memory");
IntBooleanExpression C4=
factory.greaterOrEqualsThan(C4_left, C4_right);
constraints.put("C4", C4);
hlclProgram.add(C4);
//
//declaring constraint c6


Identifier c6_left = variables.get("Memory");


Identifier c6_right_left = variables.get("Size");

NumericIdentifier c6_right_right = getValue("0");
IntBooleanExpression c6_right=
factory.greaterThan(c6_right_left, c6_right_right);
IntBooleanExpression c6=factory.doubleImplies(c6_left, c6_right);		
constraints.put("c6", c6);
hlclProgram.add(c6);
//
//declaring constraint c7


Identifier c7_left = variables.get("Processor");


Identifier c7_right_left = variables.get("Cores");

NumericIdentifier c7_right_right = getValue("0");
IntBooleanExpression c7_right=
factory.greaterThan(c7_right_left, c7_right_right);
IntBooleanExpression c7=factory.doubleImplies(c7_left, c7_right);		
constraints.put("c7", c7);
hlclProgram.add(c7);
	}
	public boolean evaluateSatisfiability(){
		// the output
		boolean evaluation= false;
		// //to transform the hllcl program into a prolog  file, 
		// //these lines are commented because they are useful for debugging 
		Hlcl2SWIProlog swiPrologTransformer = new Hlcl2SWIProlog(); 
		prologProgram = swiPrologTransformer.transform(hlclProgram);
				
		// an instance of the solver for Swiprolog 
		swiSolver= new SWIPrologSolver();
		swiSolver.setHLCLProgram(hlclProgram); //passing the hlcl program to the solver
		swiSolver.solve(); // This methhod prepares the solver 
		List<SolverSolution> solutions = swiSolver.getAllSolutions(); // Consulting if the solver has one solution
			evaluation= solutions.size()>0;
			for (SolverSolution solverSolution : solutions) {
				System.out.println(solverSolution.toString());
			}	return evaluation;
	}
	/** 
	* To obtain the NumericIdentifier representation of a value 
	* @param id the string with the value 
	* @return the NumericIdentifier 
	*/
	public NumericIdentifier getValue(String id) {	NumericIdentifier value= numbers.get(id); 
	 	if (value==null) { 
	 		if (id.equals("selected")) { 
	 			value= numbers.get("1"); 
	 		} 
	 		else if(id.equals("unselected")) {
				value= numbers.get("0"); 
			} 
			else { 
				value= factory.number(Integer.parseInt(id)); 
				numbers.put(id, value);
			}
	 	} 
	 	return value; 
	 } 
		public String getModelName() {
			return modelName;
		}
		public void setModelName(String modelName) {
			this.modelName = modelName;
		}
		public HlclFactory getFactory() {
			return factory;
		}
		public void setFactory(HlclFactory factory) {
			this.factory = factory;
		}
		public HlclProgram getHlclProgram() {
			return hlclProgram;
		}
		public void setHlclProgram(HlclProgram hlclProgram) {
			this.hlclProgram = hlclProgram;
		}
} 	