/**
 * generated by Xtext 2.12.0
 */
package org.xtext.hLCLSpecificationLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Foda UN</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.hLCLSpecificationLanguage.FodaUN#getVar <em>Var</em>}</li>
 *   <li>{@link org.xtext.hLCLSpecificationLanguage.FodaUN#getOp <em>Op</em>}</li>
 * </ul>
 *
 * @see org.xtext.hLCLSpecificationLanguage.HLCLSpecificationLanguagePackage#getFodaUN()
 * @model
 * @generated
 */
public interface FodaUN extends ConsExpression
{
  /**
   * Returns the value of the '<em><b>Var</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Var</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var</em>' attribute.
   * @see #setVar(String)
   * @see org.xtext.hLCLSpecificationLanguage.HLCLSpecificationLanguagePackage#getFodaUN_Var()
   * @model
   * @generated
   */
  String getVar();

  /**
   * Sets the value of the '{@link org.xtext.hLCLSpecificationLanguage.FodaUN#getVar <em>Var</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var</em>' attribute.
   * @see #getVar()
   * @generated
   */
  void setVar(String value);

  /**
   * Returns the value of the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Op</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op</em>' attribute.
   * @see #setOp(String)
   * @see org.xtext.hLCLSpecificationLanguage.HLCLSpecificationLanguagePackage#getFodaUN_Op()
   * @model
   * @generated
   */
  String getOp();

  /**
   * Sets the value of the '{@link org.xtext.hLCLSpecificationLanguage.FodaUN#getOp <em>Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Op</em>' attribute.
   * @see #getOp()
   * @generated
   */
  void setOp(String value);

} // FodaUN
