/**
 * generated by Xtext 2.12.0
 */
package org.xtext.hLCLSpecificationLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.hLCLSpecificationLanguage.Rule#getCondition <em>Condition</em>}</li>
 *   <li>{@link org.xtext.hLCLSpecificationLanguage.Rule#getConsequence <em>Consequence</em>}</li>
 * </ul>
 *
 * @see org.xtext.hLCLSpecificationLanguage.HLCLSpecificationLanguagePackage#getRule()
 * @model
 * @generated
 */
public interface Rule extends ConsExpression
{
  /**
   * Returns the value of the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Condition</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition</em>' containment reference.
   * @see #setCondition(Expression)
   * @see org.xtext.hLCLSpecificationLanguage.HLCLSpecificationLanguagePackage#getRule_Condition()
   * @model containment="true"
   * @generated
   */
  Expression getCondition();

  /**
   * Sets the value of the '{@link org.xtext.hLCLSpecificationLanguage.Rule#getCondition <em>Condition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition</em>' containment reference.
   * @see #getCondition()
   * @generated
   */
  void setCondition(Expression value);

  /**
   * Returns the value of the '<em><b>Consequence</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Consequence</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Consequence</em>' containment reference.
   * @see #setConsequence(Expression)
   * @see org.xtext.hLCLSpecificationLanguage.HLCLSpecificationLanguagePackage#getRule_Consequence()
   * @model containment="true"
   * @generated
   */
  Expression getConsequence();

  /**
   * Sets the value of the '{@link org.xtext.hLCLSpecificationLanguage.Rule#getConsequence <em>Consequence</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Consequence</em>' containment reference.
   * @see #getConsequence()
   * @generated
   */
  void setConsequence(Expression value);

} // Rule
