/**
 * generated by Xtext 2.12.0
 */
package org.xtext.hLCLSpecificationLanguage;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Var Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.hLCLSpecificationLanguage.HLCLSpecificationLanguagePackage#getVarDeclaration()
 * @model
 * @generated
 */
public interface VarDeclaration extends EObject
{
} // VarDeclaration
