/**
 * generated by Xtext 2.12.0
 */
package org.xtext.pLhlcl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Symbol</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.pLhlcl.PLhlclPackage#getSymbol()
 * @model
 * @generated
 */
public interface Symbol extends NonEnumerableValue
{
} // Symbol
