/**
 * generated by Xtext 2.12.0
 */
package org.xtext.pLhlcl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Variant Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.pLhlcl.PLhlclPackage#getVariantDeclaration()
 * @model
 * @generated
 */
public interface VariantDeclaration extends EObject
{
} // VariantDeclaration
